env:
  commonjs: true
  es2021: true
  node: true
  mocha: true
  browser: true
extends:
  - eslint:recommended
  - plugin:cypress/recommended
  # - google
plugins:
  - cypress
  - prettier
parserOptions:
  ecmaVersion: 12
rules: { 'prettier/prettier': 'error' }
