swagger: '2.0'
info:
  title: 'Task Service'
  description: 'API to manage task activity'
  version: '1.0.0'
  license:
    name: 'GPL-3.0'
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
host: 'localhost'
tags:
  - name: 'task'
    description: 'endpoint untuk mengedit task'
schemes:
  - 'http'
paths:
  /add:
    post:
      tags:
        - 'task'
      operationId: 'addTask'
      description: 'untuk menambahkan task baru'
      consumes:
        - 'multipart/form-data'
      produces:
        - 'application/json'
      parameters:
        - in: formData
          name: job
          type: string
          description: 'nama task baru'
          required: true
        - in: formData
          name: assignee_id
          type: number
          description: 'id pekerja yang omelakukan task'
          required: true
        - in: formData
          name: attachment
          type: file
          description: 'file informasi lanjut terkait task'
          required: true
      responses:
        '200':
          description: 'task yang baru di input'
          schema:
            $ref: '#/definitions/Task'
        '401':
          description: 'data pekerjaan baru tidak lengkap'
        '404':
          description: 'method request bukan POST'
        '500':
          description: 'terjadi kesalahan server pada server'
  /list:
    get:
      operationId: 'listTask'
      description: menampilkan list task yang ada
      tags:
        - 'task'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
        - 'text/plain'
      responses:
        '200':
          description: list task yang ada
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'
        '404':
          description: 'method request bukan GET'
        '500':
          description: 'terjadi kesalahan server pada server'
  /done:
    put:
      operationId: 'doneTask'
      description: menandakan pekerjaan selesai
      tags:
        - 'task'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: query
          name: id
          type: number
          description: 'id dari task'
      responses:
        '200':
          description: 'hasil perubahan status done menjadi true'
          schema:
            items:
              $ref: '#/definitions/TaskDone'
        '401':
          description: 'parameter id tidak ditemukan'
        '404':
          description: 'method request bukan PUT'
        '500':
          description: 'terjadi kesalahan server pada server'
  /undone:
    put:
      operationId: 'undoneTask'
      description: 'merubah status pekerjaan menjadi belum selesai'
      tags:
        - 'task'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: query
          name: id
          type: number
          description: 'id dari task'
      responses:
        '200':
          description: 'hasil perubahan status done menjadi false'
          schema:
            items:
              $ref: '#/definitions/Task'
        '401':
          description: 'parameter id tidak ditemukan'
        '404':
          description: 'method request bukan PUT'
        '500':
          description: 'terjadi kesalahan server pada server'
  /cancel:
    get:
      operationId: 'cancelTask'
      description: 'menandakan bahwa pekerjaan telah di batalkan'
      tags:
        - 'task'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: query
          name: id
          type: number
          description: 'id dari task'
      responses:
        '200':
          description: 'hasil perubahan status cancelled menjadi true'
          schema:
            items:
              $ref: '#/definitions/TaskCancel'
        '401':
          description: 'parameter id tidak ditemukan'
        '404':
          description: 'method request bukan PUT'
        '500':
          description: 'terjadi kesalahan server pada server'
  /attachment/{file}:
    get:
      tags:
        - 'task'
      operationId: 'readAttachment'
      description: 'untuk menampilkan file informasi lanjut task'
      consumes:
        - 'application/json'
      produces:
        - 'image/jpeg'
        - 'image/bmp'
        - 'image/png'
        - 'image/gif'
        - 'text/csv'
        - 'application/msword'
        - 'application/json'
        - 'application/xml'
        - 'text/plain'
        - 'text/html'
        - 'application/pdf'
        - 'application/vnd.ms-powerpoint'
        - 'application/vnd.ms-excel'
        - 'application/vnd.rar'
        - 'application/zip'
      parameters:
        - in: path
          name: file
          type: string
          required: true
          description: 'nama_file.(tipe file) -- ex: tes.txt'
      responses:
        '200':
          description: 'file berhasil ditampilkan dan dibaca'
        '400':
          description: 'request tidak sesuai'
        '404':
          description: 'error file tidak ditemukan'
        '500':
          description: 'terjadi kesalahan server pada server'
definitions:
  Task:
    type: object
    properties:
      id:
        type: number
        description: identifier pekerjaan
        example: 1
      job:
        type: string
        description: nama pekerjaan
        example: belajar
      done:
        type: boolean
        example: false
        description: 'true mendandakan pekerjaan sudah selesai'
      cancelled:
        type: boolean
        example: false
        description: 'true mendandakan pekerjaan sudah di cancel (tidak ada lagi)'
      addedAt:
        type: string
        description: 'waktu saat pekerjaan baru ditambahkan'
        example: 2021-02-09T14:19:54.697Z
      attachment:
        type: string
        description: 'nama file yang berisikan deskripsi lengkap tentang pekerjaan'
        example: belajar.txt
      assiggne:
        $ref: '#/definitions/Worker'
  TaskDone:
    type: object
    properties:
      id:
        type: number
        description: identifier pekerjaan
        example: 1
      job:
        type: string
        description: nama pekerjaan
        example: belajar
      done:
        type: boolean
        example: true
        description: 'true mendandakan pekerjaan sudah selesai'
      cancelled:
        type: boolean
        example: false
        description: 'true mendandakan pekerjaan sudah di cancel (tidak ada lagi)'
      addedAt:
        type: string
        description: 'waktu saat pekerjaan baru ditambahkan'
        example: 2021-02-09T14:19:54.697Z
      attachment:
        type: string
        description: 'nama file yang berisikan deskripsi lengkap tentang pekerjaan'
        example: belajar.txt
      assiggne:
        $ref: '#/definitions/Worker'
  TaskCancel:
    type: object
    properties:
      id:
        type: number
        description: identifier pekerjaan
        example: 1
      job:
        type: string
        description: nama pekerjaan
        example: belajar
      done:
        type: boolean
        example: false
        description: 'true mendandakan pekerjaan sudah selesai'
      cancelled:
        type: boolean
        example: true
        description: 'true mendandakan pekerjaan sudah di cancel (tidak ada lagi)'
      addedAt:
        type: string
        description: 'waktu saat pekerjaan baru ditambahkan'
        example: 2021-02-09T14:19:54.697Z
      attachment:
        type: string
        description: 'nama file yang berisikan deskripsi lengkap tentang pekerjaan'
        example: belajar.txt
      assiggne:
        $ref: '#/definitions/Worker'
  Worker:
    type: object
    properties:
      id:
        type: number
        description: identifier pekerjaan
        example: 1
      name:
        type: string
        description: nama Pekerja
        example: Annas
      age:
        type: string
        description: Umur pekerja
        example: 23
      bio:
        type: string
        description: Detail pekerja
        example: QA
      address:
        type: string
        description: Alamat pekerja
        example: Jl semarang
      photo:
        type: string
        description: Foto Pekerja
        example: 1612858486704-99.jpeg
